"""Stage 3c's record states its verdicts by its directive's rules (`docs/stages/stage-3c.md`).

The walk-forward takes too long for every CI run, so the record is regenerated by `scripts/stage3c_realtime.py`, not
here. These tests check that the record belongs to the tracked panel, pin and Stage 2 curve; that it reproduces
Stage 3b's walk-forward (same model, data and refits); and that each "shown" follows from the numbers beside it.
"""

import json
import math
import pathlib
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[1]
RECORD = ROOT / "results" / "stage3c" / "realtime.json"
STAGE_3B = ROOT / "results" / "stage3b" / "anchored.json"
MANIFEST = ROOT / "metadata" / "phase3_panel_manifest.json"


class Stage3cRecordTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.record = json.loads(RECORD.read_text(encoding="utf-8"))
        cls.stage3b = json.loads(STAGE_3B.read_text(encoding="utf-8"))

    def test_the_record_belongs_to_panel_version_1_the_pin_and_the_curve(self):
        from repo_liquidity import PARENT_COMMIT, anchored

        self.assertEqual(self.record["settings"]["panel_version"], 1)
        self.assertEqual(self.record["provenance"]["panel_sha256"],
                         json.loads(MANIFEST.read_text(encoding="utf-8"))["sha256"])
        self.assertEqual(self.record["provenance"]["parent_commit"], PARENT_COMMIT)
        self.assertEqual(self.record["anchor"]["source_sha256"], anchored.load_anchor()[1])

    def test_the_window_ends_before_2026(self):
        self.assertLessEqual(self.record["settings"]["window"][1], "2025-12-31")

    def test_the_walk_forward_reproduces_stage_3b(self):
        self.assertEqual(self.record["must_show"]["benchmark"], self.stage3b["must_show"]["benchmark"])
        self.assertEqual(self.record["reported"]["old_stability_test"]["worst"],
                         self.stage3b["must_show"]["stability"]["worst"])
        self.assertEqual(self.record["walk_forward_monthly"], self.stage3b["walk_forward_monthly"])
        self.assertEqual(self.record["refits_converged"], self.stage3b["refits_converged"])

    def test_stability_is_judged_at_half_a_point_on_the_worst_day(self):
        stability = self.record["must_show"]["stability"]
        self.assertEqual(stability["limit"], 0.005)
        self.assertEqual(stability["shown"], stability["worst"]["gap"] < stability["limit"])
        self.assertEqual(stability["shown"], not stability["days_at_or_over_limit"])

    def test_the_benchmark_interval_follows_from_the_period_variances(self):
        benchmark = self.record["must_show"]["benchmark"]
        early, late = benchmark["2018 to March 2020"], benchmark["2025"]
        difference = late["mean"] - early["mean"]
        half = 1.645 * math.sqrt(early["mean_sd"] ** 2 + late["mean_sd"] ** 2)
        self.assertAlmostEqual(benchmark["interval_90"][0], difference - half, places=5)
        self.assertEqual(benchmark["shown"], benchmark["interval_90"][0] > 0)

    def test_the_model_is_shown_only_if_both_hold(self):
        must = self.record["must_show"]
        self.assertEqual(must["shown"], must["stability"]["shown"] and must["benchmark"]["shown"])


if __name__ == "__main__":
    unittest.main()
