"""Stage 6's records state their eligibility by the plan's rules (`docs/stages/stage-6.md`).

The walk-forwards take minutes (A) to hours (B), so the records are regenerated by `scripts/stage6_ab.py`, not here.
These tests check that each record belongs to the tracked panel and pin, scored nothing after 2025-12-31, and that each
verdict follows from the numbers beside it.
"""

import json
import pathlib
import unittest

from repo_liquidity import deployable

ROOT = pathlib.Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results" / "stage6"
MANIFEST = ROOT / "metadata" / "phase3_panel_v3_manifest.json"


class Stage6RecordTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.records = {name: json.loads((RESULTS / f"{name}.json").read_text(encoding="utf-8")) for name in "ab"}

    def test_the_records_belong_to_panel_version_3_and_the_pin(self):
        from repo_liquidity import PARENT_COMMIT

        digest = json.loads(MANIFEST.read_text(encoding="utf-8"))["sha256"]
        for name, record in self.records.items():
            self.assertEqual(record["provenance"]["phase3_panel_sha256"], digest, name)
            self.assertEqual(record["provenance"]["parent_commit"], PARENT_COMMIT, name)
            self.assertFalse(record["provenance"]["tree_modified"], name)

    def test_nothing_is_scored_after_2025(self):
        for name, record in self.records.items():
            self.assertLessEqual(max(record["path"]), "2025-12-31", name)

    def test_the_verdicts_follow_from_the_numbers(self):
        for name, record in self.records.items():
            eligibility = record["eligibility"]
            gaps_ok = eligibility["stability"]["worst"]["gap"] < deployable.STABILITY_LIMIT
            widths_ok = eligibility["intervals"]["median"] < deployable.WIDTH_LIMIT
            self.assertEqual(eligibility["stability"]["shown"], gaps_ok, name)
            self.assertEqual(eligibility["intervals"]["shown"], widths_ok, name)
            self.assertFalse(eligibility["distribution_account"]["computed"], name)
            self.assertEqual(eligibility["eligible"], None if gaps_ok and widths_ok else False, name)

    def test_the_score_is_recomputable_from_the_path(self):
        from datetime import date

        for name, record in self.records.items():
            path = record["path"]
            days = [day for day in path if day >= deployable.EVENTS_FROM.isoformat()]
            self.assertEqual(record["score"]["from_2019_09_17"]["days"], len(days), name)

    def test_every_b_refit_is_in_the_checkpoint(self):
        checkpoint = [json.loads(line) for line in
                      (RESULTS / "b_checkpoint.jsonl").read_text(encoding="utf-8").splitlines()]
        self.assertEqual(sorted(entry["cutoff"] for entry in checkpoint),
                         sorted(refit["cutoff"] for refit in self.records["b"]["refits"]))


if __name__ == "__main__":
    unittest.main()
