"""Stage 4's records state their verdicts by the plan's rules (`docs/stages/stage-4.md`).

The comparison takes minutes, so the records are regenerated by `scripts/stage4_compare.py` and
`scripts/stage4_brier.py`, not here. These tests check that the records belong to the tracked panel and pin, were
made from a clean tree, scored nothing after 2025-12-31, reproduce the published records, and that each label follows
from the numbers beside it.
"""

import json
import pathlib
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results" / "stage4"
MANIFEST = ROOT / "metadata" / "phase3_panel_v3_manifest.json"


def _label(mean, lower, upper):
    """evaluation.md's pass rule, as the parent's `crps_verdict`."""
    if mean > 0 and lower > 0:
        return "shown better"
    if upper < 0:
        return "shown worse"
    return "not shown"


class Stage4RecordTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.records = {name: json.loads((RESULTS / f"{name}.json").read_text(encoding="utf-8"))
                       for name in ("curve_pass", "comparison", "brier")}

    def test_the_records_belong_to_panel_version_3_and_the_pin_from_a_clean_tree(self):
        from repo_liquidity import PANEL_SHA256, PARENT_COMMIT

        digest = json.loads(MANIFEST.read_text(encoding="utf-8"))["sha256"]
        for name, record in self.records.items():
            provenance = record["provenance"]
            self.assertEqual(provenance["phase3_panel_sha256"], digest, name)
            self.assertEqual(provenance["parent_commit"], PARENT_COMMIT, name)
            self.assertEqual(provenance["parent_panel_sha256"], PANEL_SHA256, name)
            self.assertFalse(provenance["tree_modified"], name)

    def test_nothing_is_scored_after_2025(self):
        per_origin = self.records["comparison"]["parent_document"]["comparison"]["per_origin"]
        self.assertLessEqual(max(entry["scored_date"] for entry in per_origin), "2025-12-31")

    def test_the_baseline_arms_reproduce_the_published_records(self):
        crps = self.records["comparison"]["must_show_1_reproduction"]
        self.assertTrue(crps["held"])
        self.assertLessEqual(crps["largest_gap_bp"], crps["tolerance_bp"])
        brier = self.records["brier"]["model_a_reproduces_published"]
        self.assertTrue(brier["held"])
        self.assertIn("5", brier["taus_checked"])

    def test_the_verdict_follows_from_the_interval(self):
        primary = self.records["comparison"]["primary"]
        interval = primary["interval"]
        self.assertEqual(self.records["comparison"]["verdict"],
                         _label(primary["mean_difference_bps"], interval["lower"], interval["upper"]))
        self.assertAlmostEqual(primary["mean_difference_bps"], primary["crps_a_bps"] - primary["crps_b_bps"],
                               places=9)

    def test_only_the_amendments_refit_carried_a_curve(self):
        """The curve pass failed at one refit; the amendment carries the last fitted curve there and nowhere else."""
        failures = [entry["cutoff"] for entry in self.records["curve_pass"]["refits"] if "failed" in entry]
        for name in ("comparison", "brier"):
            carried = [entry["cutoff"] for entry in self.records[name]["curves"] if entry["carried_from"]]
            self.assertEqual(carried, failures, name)
        self.assertEqual(len(self.records["comparison"]["curves"]), len(self.records["curve_pass"]["refits"]))


if __name__ == "__main__":
    unittest.main()
