"""Stage 3b's record states its verdicts by the directive's rules (`docs/stages/stage-3b.md`).

The walk-forward takes too long for every CI run, so the record is regenerated by `scripts/stage3b_anchored.py`, not
here. These tests check that the tracked record belongs to the tracked panel, pin and Stage 2 curve, ends before the
lockbox, and that each "shown" follows from the numbers beside it.
"""

import json
import math
import pathlib
import unittest

ROOT = pathlib.Path(__file__).resolve().parents[1]
RECORD = ROOT / "results" / "stage3b" / "anchored.json"
MANIFEST = ROOT / "metadata" / "phase3_panel_manifest.json"


class Stage3bRecordTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        cls.record = json.loads(RECORD.read_text(encoding="utf-8"))

    def test_the_record_belongs_to_the_tracked_panel_pin_and_curve(self):
        from repo_liquidity import PARENT_COMMIT, anchored

        manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
        anchor, digest = anchored.load_anchor()
        self.assertEqual(self.record["provenance"]["panel_sha256"], manifest["sha256"])
        self.assertEqual(self.record["provenance"]["parent_commit"], PARENT_COMMIT)
        self.assertEqual(self.record["anchor"]["source_sha256"], digest)
        self.assertEqual((self.record["anchor"]["intercept"], self.record["anchor"]["slope"]),
                         (anchor.intercept, anchor.slope))

    def test_the_window_ends_before_2026(self):
        self.assertLessEqual(self.record["settings"]["window"][1], "2025-12-31")

    def test_stability_is_judged_at_half_a_point(self):
        stability = self.record["must_show"]["stability"]
        self.assertEqual(stability["limit"], 0.005)
        self.assertEqual(stability["shown"], stability["worst"]["difference"] < stability["limit"])

    def test_the_benchmark_interval_follows_from_the_period_variances(self):
        benchmark = self.record["must_show"]["benchmark"]
        early, late = benchmark["2018 to March 2020"], benchmark["2025"]
        difference = late["mean"] - early["mean"]
        half = 1.645 * math.sqrt(early["mean_sd"] ** 2 + late["mean_sd"] ** 2)
        self.assertAlmostEqual(benchmark["difference"], difference, places=5)
        self.assertAlmostEqual(benchmark["interval_90"][0], difference - half, places=5)
        self.assertEqual(benchmark["shown"], benchmark["interval_90"][0] > 0)

    def test_every_refit_keeps_its_best_start(self):
        for cutoff, refit in self.record["refit_params"].items():
            by_start = refit["loglike_by_start"]
            self.assertEqual(by_start[refit["winning_start"]], max(by_start.values()), cutoff)

    def test_the_model_is_shown_only_if_both_hold(self):
        must = self.record["must_show"]
        self.assertEqual(must["shown"], must["stability"]["shown"] and must["benchmark"]["shown"])

    def test_the_directive_sensitivities_are_reported(self):
        self.assertEqual(set(self.record["sensitivities"]),
                         {"scale_0.002", "scale_0.01", "legal_breaks_only", "steps_only_drift_held_at_0",
                          "no_calendar_terms", "jump_also_at_2025-12-11", "jumps_only_at_slr_end",
                          "corridor_from_tgcr"})


if __name__ == "__main__":
    unittest.main()
